### ISSUE TITLE
Migrate code to new asm! syntax

### ISSUE THREAD

**Issue by dreamer** [o8vm/rust_dos#1]
I was hoping to experiment with this repo a little bit to see if I could use Rust for implementing new built-in DOS commands for [dosbox-staging](https://github.com/dosbox-staging/dosbox-staging), but ATM it does not compile.

Nightly transitioned to new `asm!` syntax; old syntax can still be used via `llvm_asm!` (but somehow it does not work for me), but perhaps it would be better to move to new syntax right away.

https://github.com/rust-lang/rust/issues/70173
https://github.com/rust-lang/rust/pull/68404

Right now, the code fails to compile with several errors like this one:
```
error: the legacy LLVM-style asm! syntax is no longer supported
 --> src/dos/io.rs:4:9
  |
4 |           asm!("xorl %eax, %eax
  |           ^---
  |           |
  |  _________help: replace with: `llvm_asm!`
  | |
5 | |               inb  %dx,  %al"
6 | |              : "={al}"(ret)
7 | |              : "{dx}"(port)
8 | |             );
  | |______________^
  |
  = note: consider migrating to the new asm! syntax specified in RFC 2873
  = note: alternatively, switch to llvm_asm! to keep your code working as it is
```

**Comment by o8vm** [comment]
Thanks for the report on the issue. I think I'm going to move the `asm!` macro to `llvm_asm!` once and then to the new `asm!`.

**Comment by o8vm** [comment]
New asm syntax is supported, and the build environment has been redesigned. This issue has been fixed and the build is now easier. If the issue persists, please open a new issue.
