### ISSUE TITLE
Fail to build outside a clone of the repository.

### ISSUE THREAD

**Issue by nitsuga5124** [o8vm/rust_dos#7]
Making a new crate and copying the required files over to the new crate leads to: "language item required, but not found: `eh_personality`" when building.
There's a video showing the steps on how to reproduce this.

https://user-images.githubusercontent.com/8344197/114394487-8cd5f380-9b9b-11eb-93c6-ab071bc8c0e7.mp4

Using Arch Linux on an Intel i7 4790, rustc `rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)` and `GNU ld 2.36.1`
`cross` is not required to reproduce the issue, mentioned in #4, as cargo was being used in this case.

**Comment by o8vm** [comment]
The `.cargo` directory is important for the build. Make sure to copy this directory as well.

example:
```shell
cp -r /path/to/rust_dos/.cargo /path/to/your_project/
```

**Comment by nitsuga5124** [comment]
Copying `.cargo` over fixed the build; this should probably be mentioned on the readme.

**Comment by o8vm** [comment]
I am writing an explanatory article for this project. I'll add it to the readme after it's published.
